package com.certidevs.excepciones;

public class Main1 {

    public static void main(String[] args) {


        try {
            int resultado = 5 / 0;
        } catch (ArithmeticException e) {
            System.out.println("Divisi贸n incorrecta");
        }
//        try {
//            int resultado = 5 / 0;
//        } catch (IndexOutOfBoundsException e) { // Excepci贸n diferente, no la captura
//            System.out.println("Divisi贸n incorrecta");
//        }
        try {
            int resultado = 5 / 0;
        } catch (Exception e) { // Polimorfismo
            System.out.println("Divisi贸n incorrecta");
        }

        System.out.println("Continuamos");
    }
}
